### ISSUE TITLE
Add project.toml for project configuration variables

### ISSUE THREAD

**Issue by haata** [kiibohd/kiibohd-firmware#2]
We need a better way to store useful project variables.

Mainly the USB VID and PID as they currently live inside build.rs.
We also need to use the VID and PID for flashing so being able to query it is useful.

**Comment by hiszd** [comment]
Is the goal here to have values added to the Cargo.toml to configure these properties, or to have a library somewhere that stores the associated VID and PID data for each product in one place?

**Comment by haata** [comment]
Ideally, add the vid and pid to Cargo.toml, but I'm not sure this can be done easily.
Another option would be to use some sort of project.toml instead.

**Comment by haata** [comment]
After integrating with cargo-make, I've created https://github.com/kiibohd/kiibohd-firmware/blob/main/hexgears/gemini/project.env

Ideally, build.rs could read this file (I'm pretty sure is just a shell script, but not 100%) and retrieve BOOT_VID and BOOT_PID.

**Comment by haata** [comment]
Fixed in PR #6
